#!/usr/bin/env bash
# AI Agent 执行步骤（由 run_all.py 提示，需人工/AI 执行）

echo "========================================"
echo "test_01_pdf_parse — AI 执行步骤"
echo "========================================"
echo ""
echo "1. 解析 PDF 作业："
echo "   python3 -c \""
echo "   import pdfplumber, json, re"
echo "   ... (参考 do-homework.md 第 2 节)"
echo "   \""
echo "   输出：homework_parsed.json"
echo ""
echo "2. 生成解答："
echo "   创建 Solver Agent，读取 homework_parsed.json，输出 answers.json"
echo ""
echo "3. 渲染（可选）："
echo "   Markdown -> HTML -> PDF"
echo ""
